test: local ICP Ninja example deployment (#217)
(XC-454) Test local deployment of ICP Ninja `basic_solana` example. This
simulates what a user would do when downloading their project from ICP
Ninja and deploying it locally. This includes downloading the latest SOL
RPC canister WASM file from GitHub and changing the value of
`solana_network ` in the `init_args` in `dfx.json` from `Devnet ` to
`Custom = record { url = \"https://api.devnet.solana.com\"; headers =
null }` as outlined in the `basic_solana` README.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -114,6 +114,37 @@ jobs:
       - name: 'Run unit tests'
         run: cargo test --locked --workspace --exclude basic_solana --exclude sol_rpc_int_tests --exclude sol_rpc_e2e_tests
 
+  icp-ninja-tests:
+    runs-on: ubuntu-latest
+    steps:
+      - name: 'Checkout'
+        uses: actions/checkout@v4
+
+      - name: 'Install dfx'
+        uses: dfinity/setup-dfx@e50c04f104ee4285ec010f10609483cf41e4d365
+        with:
+          dfx-version: "0.27.0"
+
+      - name: 'Confirm dfx successful installation'
+        run: dfx --version
+
+      - name: 'Use free Solana RPC provider'
+        working-directory: examples/basic_solana/ninja
+        run: |
+          sed -i 's|solana_network = opt variant { Devnet }|solana_network = opt variant { Custom = record { url = \\"https://api.devnet.solana.com\\"; headers = null } }|g' dfx.json
+
+      - name: "Deploy locally"
+        working-directory: examples/basic_solana/ninja
+        run: |
+          dfx start --clean --background
+          dfx deploy
+          out=$(dfx canister call basic_solana solana_account --output json)
+          echo "$out"
+          echo "$out" | grep -Eq "[1-9A-HJ-NP-Za-km-z]{32,44}" || { echo "❌ Call to 'solana_account' failed"; exit 1; }
+          out=$(dfx canister call basic_solana get_balance --output json)
+          echo "$out"
+          echo "$out" | grep -Eq "[0-9]+(_[0-9]+)*" || { echo "❌ Call to 'get_balance' failed"; exit 1; }
+
   integration-tests:
     needs: [ reproducible-build ]
     runs-on: ubuntu-22.04
@@ -213,10 +244,10 @@ jobs:
           dfx deploy
           out=$(dfx canister call basic_solana solana_account --output json)
           echo "$out"
-          echo "$out" | grep -E "[1-9A-HJ-NP-Za-km-z]{32,44}" > /dev/null || { echo "❌ Call to 'solana_account' failed"; exit 1; }
+          echo "$out" | grep -Eq "[1-9A-HJ-NP-Za-km-z]{32,44}" || { echo "❌ Call to 'solana_account' failed"; exit 1; }
           out=$(dfx canister call basic_solana get_balance --output json)
           echo "$out"
-          echo "$out" | grep -E "[0-9]+(?:_[0-9]+)*" > /dev/null || { echo "❌ Call to 'get_balance' failed"; exit 1; }
+          echo "$out" | grep -Eq "[0-9]+(_[0-9]+)*" || { echo "❌ Call to 'get_balance' failed"; exit 1; }
 
       - name: "Deploy SOL RPC Canister"
         run: |
