XC-335: Fix account regex

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -168,10 +168,10 @@ jobs:
           dfx deploy
           out=$(dfx canister call basic_solana solana_account --output json)
           echo "$out"
-          echo "$out" | grep -E "\d+(?:_\d+)*" > /dev/null || { echo "❌ Call to `solana_account` failed"; exit 1; }
+          echo "$out" | grep -E "[1-9A-HJ-NP-Za-km-z]{32,44}" > /dev/null || { echo "❌ Call to 'solana_account' failed"; exit 1; }
           out=$(dfx canister call basic_solana get_balance --output json)
           echo "$out"
-          echo "$out" | grep -E "\d+(?:_\d+)*" > /dev/null || { echo "❌ Call to `get_balance` failed"; exit 1; }
+          echo "$out" | grep -E "\d+(?:_\d+)*" > /dev/null || { echo "❌ Call to 'get_balance' failed"; exit 1; }
 
       - name: "Deploy SOL RPC Canister"
         run: |
