test: add `basic_solana` deployment tests (#150)
(XC-335) Add tests for `basic_solana` deployment (local and to IC) to
the CI pipeline.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -43,11 +43,12 @@ jobs:
     steps:
       - name: 'Checkout'
         uses: actions/checkout@v4
-      - name: Docker build
+
+      - name: 'Docker build'
         run: |
           ./scripts/docker-build
 
-      - name: 'Archive Artifact'
+      - name: 'Archive artifact'
         uses: actions/upload-artifact@v4
         with:
           name: sol_rpc_canister.wasm.gz
@@ -75,7 +76,7 @@ jobs:
       - name: 'Checkout'
         uses: actions/checkout@v4
 
-      - name: 'Download Artifacts'
+      - name: 'Download artifacts'
         uses: actions/download-artifact@v4
         with:
           name: sol_rpc_canister.wasm.gz
@@ -134,7 +135,7 @@ jobs:
       - name: 'Checkout'
         uses: actions/checkout@v4
 
-      - name: 'Download Artifacts'
+      - name: 'Download artifacts'
         uses: actions/download-artifact@v4
         with:
           name: sol_rpc_canister.wasm.gz
@@ -142,7 +143,7 @@ jobs:
       - name: 'Install dfx'
         uses: dfinity/setup-dfx@e50c04f104ee4285ec010f10609483cf41e4d365
         with:
-          dfx-version: "0.25.0"
+          dfx-version: "0.27.0"
 
       - name: 'Confirm dfx successful installation'
         run: dfx --version
@@ -160,6 +161,18 @@ jobs:
           dfx identity set-wallet --ic --force "${{ env.wallet_canister_id }}"
           dfx wallet balance --ic
 
+      - name: "Deploy basic_solana locally"
+        working-directory: examples/basic_solana/local
+        run: |
+          dfx start --clean --background
+          dfx deploy
+          out=$(dfx canister call basic_solana solana_account --output json)
+          echo "$out"
+          echo "$out" | grep -E "[1-9A-HJ-NP-Za-km-z]{32,44}" > /dev/null || { echo "❌ Call to 'solana_account' failed"; exit 1; }
+          out=$(dfx canister call basic_solana get_balance --output json)
+          echo "$out"
+          echo "$out" | grep -E "[0-9]+(?:_[0-9]+)*" > /dev/null || { echo "❌ Call to 'get_balance' failed"; exit 1; }
+
       - name: "Deploy SOL RPC Canister"
         run: |
           wallet="${{ env.wallet_canister_id }}"
@@ -171,7 +184,7 @@ jobs:
         working-directory: canister/ci
         run: ../scripts/examples.sh 2>&1 | tee e2e_examples.log
 
-      - name: "Detect Inconsistent Results"
+      - name: "Detect inconsistent results"
         working-directory: canister/ci
         run: cat e2e_examples.log | grep -q -e Inconsistent && exit 1 || exit 0
 
